language: python
python:
  - 3.6
services:
  - docker

script:
  - ./run_tests.sh

after_script:
  - codecov

after_success:
  - test $TRAVIS_BRANCH = "master" && bash ./deploy.sh

before_deploy: |-
  git tag $(grep -i version ouroboros/__init__.py | cut -d= -f2 | sed "s/'//g")

deploy:
  - provider: releases
    api_key: $github_api_key
    skip_cleanup: true
    on:
      branch: master

