language: python
python:
  - 3.6
services:
  - docker

script:
  - ./run_tests.sh

after_script:
  - codecov

deploy:
  provider: script
  script:
    - export VERSION=$(grep -i version ouroboros/__init__.py | awk -F= '{gsub("\047",""); print $2})
    - docker login -u=circa10a -p=$docker_password
    - docker build -t circa10a/ouroboros .
    - docker push circa10a/ouroboros
    - docker tag circa10a/ouroboros circa10a/ouroboros:$VERSION
    - docker push circa10a/ouroboros circa10a/ouroboros:$VERSION
  on:
    branch: master