sudo: true
dist: xenial
language: python
python:
  - 3.7.2
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce

script:
  - pip install flake8 && flake8 --max-line-length 120 *.py pyouroboros/
  - python3 ./ouroboros -l debug --run-once

deploy:
  - provider: pypi
    user: pyouroboros
    password: $PYPI_PASSWORD
    skip_existing: true
    on:
      branch: master
  - provider: script
    script: bash deploy.sh
    on:
      branch: master
  - provider: script
    script: bash deploy.sh
    on:
      branch: develop