language: python
python:
  - 3.6
services:
  - docker

script:
  - ./run_tests.sh

after_script:
  - codecov

before_deploy: |-
  git config --local user.name "circa10a" && \
  git config --local user.email "caleblemoine@gmail.com" && \
  git tag $(grep -i version ouroboros/__init__.py | cut -d= -f2 | sed "s/'//g")

deploy:
  - provider: releases
    api_key: $github_api_key
    skip_cleanup: true
    on:
      branch: master

after_success:
  script: bash ./deploy.sh
    on:
      branch: master